name: MissingNo
description: Lunch Club specific shenanigans.
author: Aiden
version: 1.4.2
main: one.lunchclub.MissingNo
api-version: 1.18

commands:
  name:
    description: Set your name for the chat listener
    usage: /name <name>
    permission: missingno.name
  inventory:
    description: View the inventory of a player
    usage: /inventory <player>
    permission: missingno.investigate
  hat:
    description: Equip a hat
    usage: /hat
    permission: missingno.hat