name: MissingNo
description: Lunch Club specific shenanigans.
author: Aiden
version: 1.4.3
main: one.lunchclub.MissingNo
api-version: 1.18

commands:
  name:
    description: Set your name for the chat listener
    usage: /name <name>
    permission: missingno.name
  hat:
    description: Equip a hat
    usage: /hat
    permission: missingno.hat
  togglechairs:
    description: Toggle SuperChairs chairs.use permission
    usage: /togglechairs
    permission: missingno.togglechairs